# The title of your homepage
title = "Your Homepage Title"
favicon_url = "./favicon.ico"

[background]
# The type of background for your homepage
# Mode			| Result
# --------------|--------------------
# triangles		| Random triangles
# static		| Static background image
mode = "triangles"

# If background.mode is set to static, this sets the background URL.
# Defaults to a random image from the "calm wallpapers" 
# Unsplash collection.
# Has no effect if background_mode isn't set to static.
url = "https://source.unsplash.com/collection/137627/1920x1080"


# Items that should appear on your homepage
# See https://fontawesome.com/icons?d=gallery&m=free for a reference of supported Icons
# TODO: Add ForkAwesome and image support here.

[[items]]
label = "GitHub"
icon = "fab fa-github"
link = "https://github.com/Swagielka"

[[items]]
label = "Twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/Kukielka_"

[[items]]
label = "Docker Hub"
icon = "fab fa-docker"
link = "https://hub.docker.com/u/kukielka/"

[[items]]
# The text to show on hover.
label = "Starbeamrainbowlabs"
# Optional. Defines the kind of icon to display. Supported values:
# fontawesome		The default. The value of icon should be the classes of a FontAwesome icon.
# image				The value of icon should be the URL of a static image to display.
icon_mode = "image"
# The icon to display. The exact value depends on the value of icon_mode. 
icon = "https://starbeamrainbowlabs.com/images/sbrl/SBRL-Large-620.png"
# The link to send users to when the icon is clicked.
link = "https://starbeamrainbowlabs.com/"


# Example of a folder:

[[folders]]
# Currently name and folders.background don't do anything yet
name = "Websites"
	[folders.background]
	mode = "static"
	url = "https://source.unsplash.com/collection/137627/1920x1080"

	[[folders.items]]
	label = "GitHub"
	icon = "fab fa-github"
	link = "https://github.com/Swagielka"

	[[folders.items]]
	label = "Twitter"
	icon = "fab fa-twitter"
	link = "https://twitter.com/Kukielka_"

	[[folders.items]]
	label = "Docker Hub"
	icon = "fab fa-docker"
	link = "https://hub.docker.com/u/kukielka/"

	[[folders.items]]
	label = "Docker Hub"
	# icon = "fab fa-docker"
	icon_mode = "image"
	icon = "https://starbeamrainbowlabs.com/images/logos/docker.png"
	link = "https://hub.docker.com/u/kukielka/"

	[[folders.items]]
	label = "Docker Hub"
	# icon = "fab fa-docker"
	icon_mode = "image"
	icon = "https://starbeamrainbowlabs.com/images/logos/docker.png"
	link = "https://hub.docker.com/u/kukielka/"
